name: Danger actions
'on':
  pull_request:
    types: [opened, edited, reopened, synchronize, assigned, unassigned, review_requested, review_request_removed]
jobs:
  danger-ci:
    name: Danger CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - uses: actions/setup-node@60c11408891ef62846c29c28c2374afe5c91fad5 # master
        with:
          node-version: 12.x
        env:
          RUNNER_TEMP: /tmp
      - name: yarn install
        run: yarn install
      - name: Danger CI
        uses: vtex/danger@eb08f92052b56ef568a5c24d9e55c1eaabded641 # master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          REQUIRE_CHANGELOG_VERSION: false
